"use client";

import { useMemo, useState } from "react";
import dynamic from "next/dynamic";
import { Activity as ActivityIcon, Clock, FileText } from "lucide-react";
import { ApiError } from "@/lib/api-client";
import { useContextFile } from "@/lib/hooks/use-context";
import { useManagedTasks } from "@/lib/hooks/use-managed-tasks";
import { useActivitySources } from "@/lib/hooks/use-activity-sources";
import { useSnapshots } from "@/lib/hooks/use-snapshots";
import { extractSources, mergeActivitySources } from "@/lib/sources";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { EmptyState } from "@/components/shared/empty-state";
import { QueryResult } from "@/components/shared/query-result";
import { cn, formatRelativeTime } from "@/lib/utils";

const RenderedMarkdown = dynamic(
  () =>
    import("@/components/knowledge/rendered-markdown").then(
      (m) => m.RenderedMarkdown,
    ),
  {
    ssr: false,
    loading: () => (
      <div className="space-y-2 py-2">
        {Array.from({ length: 5 }).map((_, i) => (
          <div
            key={i}
            className="h-4 animate-pulse rounded bg-muted/30"
            style={{ width: `${65 + ((i * 11) % 30)}%` }}
          />
        ))}
      </div>
    ),
  },
);

/**
 * Memory → Activity (docs/design/21-management-registry-and-entities.md
 * §14.1).
 *
 * Per-source view of `_activity/<source>.md` (L3, auto-generated by the
 * activity-view reconciler). The sidebar lists the union of:
 *
 *   - active managed tasks (every `App` value in Section B), and
 *   - recently-stopped sources still inside the reconciler's 90-day
 *     window (their `_activity/<source>.md` is on disk but the row is
 *     gone from `managed_tasks`) — surfaced via `GET /activity-sources`
 *     so the dashboard mirrors the daemon's enumeration exactly.
 *
 * Stopped entries are visually distinct (a `stopped` badge instead of
 * the active count). Files the reconciler has not produced yet show a
 * "no activity recorded" hint instead of a 404.
 */

export function ActivityContent() {
  const tasksQuery = useManagedTasks();
  const activitySourcesQuery = useActivitySources();
  const sources = useMemo(
    () =>
      mergeActivitySources(
        extractSources(tasksQuery.data?.items),
        activitySourcesQuery.data?.items,
      ),
    [tasksQuery.data, activitySourcesQuery.data],
  );
  const [selected, setSelected] = useState<string | null>(null);

  // Default-select the first ACTIVE source so the user lands on a live
  // task rather than a recently-stopped one (the merged list is sorted
  // by label, not status — alphabetic order could otherwise put a
  // stopped entry first).
  const effectiveSelected =
    selected ??
    sources.find((s) => s.status === "active")?.normalized ??
    sources[0]?.normalized ??
    null;

  return (
    <div className="grid h-full grid-cols-1 gap-4 md:grid-cols-[16rem_1fr]">
      <Card className="flex h-full min-h-0 flex-col p-3">
        <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
          Sources
        </h3>
        <QueryResult
          isLoading={tasksQuery.isLoading}
          isError={tasksQuery.isError}
          error={tasksQuery.error as Error | null}
          onRetry={() => tasksQuery.refetch()}
        >
          {sources.length === 0 ? (
            <EmptyState
              icon={ActivityIcon}
              title="No sources"
              description="Active managed tasks define which sources have an activity view."
            />
          ) : (
            <ScrollArea className="min-h-0 flex-1">
              <ul className="space-y-0.5">
                {sources.map((source) => {
                  const active = source.normalized === effectiveSelected;
                  const isStopped = source.status === "stopped";
                  return (
                    <li key={source.normalized}>
                      <button
                        type="button"
                        onClick={() => setSelected(source.normalized)}
                        className={cn(
                          "flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm transition-colors",
                          active
                            ? "bg-primary/10 text-primary font-medium"
                            : "text-muted-foreground hover:bg-accent hover:text-foreground",
                          isStopped && !active && "opacity-70",
                        )}
                        title={
                          isStopped
                            ? "Stopped — kept for the 90-day activity window."
                            : undefined
                        }
                      >
                        <FileText className="h-3.5 w-3.5 shrink-0" />
                        <span className="flex-1 truncate">{source.label}</span>
                        {isStopped ? (
                          <Badge variant="amber" className="shrink-0 text-[10px]">
                            stopped
                          </Badge>
                        ) : (
                          <Badge variant="gray" className="shrink-0">
                            {source.count}
                          </Badge>
                        )}
                      </button>
                    </li>
                  );
                })}
              </ul>
            </ScrollArea>
          )}
        </QueryResult>
      </Card>

      <Card className="flex h-full min-h-0 flex-col p-4">
        {effectiveSelected ? (
          <ActivityFilePanel source={effectiveSelected} />
        ) : (
          <EmptyState
            icon={ActivityIcon}
            title="No source selected"
            description="Pick a source on the left to view its activity log."
          />
        )}
      </Card>
    </div>
  );
}

function ActivityFilePanel({ source }: { source: string }) {
  // The activity-view runner snapshots with the `.md`-bearing relative
  // path (`_activity/<source>.md`) — see core/context/activity-view-
  // runner.ts:writeWithSnapshot. The /context API normalizes either
  // form, but /snapshots/* is an exact `file_path` match, so the same
  // string MUST be passed to both reads. The dropped `.md` was silently
  // hiding every history entry.
  const path = `_activity/${source}.md`;
  const file = useContextFile(path);
  const snapshots = useSnapshots(path);
  const [showSnapshots, setShowSnapshots] = useState(false);

  if (file.isLoading) {
    return (
      <div className="space-y-2 py-2">
        {Array.from({ length: 5 }).map((_, i) => (
          <div
            key={i}
            className="h-4 animate-pulse rounded bg-muted/30"
            style={{ width: `${50 + ((i * 11) % 30)}%` }}
          />
        ))}
      </div>
    );
  }

  if (file.error) {
    const status = (file.error as ApiError | undefined)?.status;
    if (status === 404) {
      return (
        <EmptyState
          icon={Clock}
          title="No activity recorded yet"
          description={
            "The activity-view reconciler will produce " +
            path +
            " after the next scheduled run."
          }
        />
      );
    }
    return (
      <p className="text-sm text-destructive">
        Failed to load: {(file.error as Error).message}
      </p>
    );
  }

  if (!file.data) return null;

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="mb-3 flex items-start justify-between gap-3">
        <div>
          <h3 className="text-sm font-semibold">
            <code className="font-mono text-xs">{path}</code>
          </h3>
          <p className="text-[11px] text-muted-foreground">
            Auto-generated · last modified{" "}
            {formatRelativeTime(file.data.lastModified)}
          </p>
        </div>
        {snapshots.data && snapshots.data.snapshots.length > 0 && (
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => setShowSnapshots((v) => !v)}
          >
            {showSnapshots
              ? "Hide history"
              : `Show history (${snapshots.data.snapshots.length})`}
          </Button>
        )}
      </div>

      {showSnapshots && snapshots.data && (
        <SnapshotsList snapshots={snapshots.data.snapshots} />
      )}

      <ScrollArea className="min-h-0 flex-1">
        <RenderedMarkdown content={file.data.content} />
      </ScrollArea>
    </div>
  );
}

interface SnapshotItem {
  id: number;
  trigger: string;
  created_at: string;
}

function SnapshotsList({ snapshots }: { snapshots: SnapshotItem[] }) {
  return (
    <ul className="mb-3 space-y-1 rounded-md border border-border/40 bg-muted/30 p-2 text-[11px]">
      {snapshots.slice(0, 10).map((snap) => (
        <li
          key={snap.id}
          className="flex items-center justify-between gap-2 px-1 py-0.5"
        >
          <span className="text-muted-foreground">
            {formatRelativeTime(snap.created_at)}
          </span>
          <span className="text-muted-foreground/70">{snap.trigger}</span>
        </li>
      ))}
    </ul>
  );
}
